### ISSUE TITLE
Defaults to 32 bit functions on 64 bit installation of Python

### ISSUE THREAD

**Issue by thdb-theo** [trevorprater/pymorton#5]
Because sys.maxint no longer exists, the code uses the 32 bit version of the functions. interleaving 0xffff and 0xffff yields the same result as 0xfffff and 0xffff since it's using the 32 bit function and the result should be 33 bits long.

![Screenshot from 2023-03-29 17-15-04](https://user-images.githubusercontent.com/26367553/228585836-31310d03-ec74-4277-9bdd-08289108294b.png)

The issue lies here:
https://github.com/trevorprater/pymorton/blob/f248683c19d90e904193c58bbd03e77bc2c43768/pymorton/pymorton.py#L92

**Comment by jeremyh3** [comment]
I also have this issue.   Just have some very large numbers (64bit) that need to get the morton index for (geospatial mapping stuff), and it fails to function if the numbers are too large.
